### ISSUE TITLE
Failed to check version of northflank CLI

### ISSUE THREAD

**Issue by ReaJason** [northflank/deploy-to-northflank#1]
failed in https://github.com/ReaJason/MemShellParty/actions/runs/13097307779/job/36541205379

```yaml
  deploy-northflank:
    name: Deploy to Northflank
    needs: [ docker-push ]
    runs-on: ubuntu-latest
    steps:
      - uses: northflank/deploy-to-northflank@v1
        with:
          northflank-api-key: ${{ secrets.NORTHFLANK_API_KEY }}
          project-id: ${{ vars.NORTHFLANK_PROJECT_ID }}
          service-id: ${{ vars.NORTHFLANK_SERVICE_ID }}
          image-path: ${{ vars.NORTHFLANK_IMAGE_PATH }}
          credentials-id: ${{ vars.NORTHFLANK_CREDENTIALS_ID }}
```

<img width="1150" alt="Image" src="https://github.com/user-attachments/assets/ffc2231e-ecbb-40d3-bf4c-588daf0d75da" />

**Comment by ReaJason** [comment]
api is work
```yaml
  deploy-northflank:
    name: Deploy to Northflank
    needs: [ docker-push ]
    runs-on: ubuntu-latest
    env:
      NORTHFLANK_API_KEY: ${{ secrets.NORTHFLANK_API_KEY }}
    steps:
      - name: Update Deployment
        run: |
          curl --header "Content-Type: application/json" \
               --header "Authorization: Bearer $NORTHFLANK_API_KEY" \
               --request POST \
               --data '{"external":{"imagePath":"docker.io/reajason/memshell-party:latest","credentials":"docker-hub"},"docker":{"configType":"default"}}' \
               https://api.northflank.com/v1/projects/memshellparty/services/memshellparty/deployment
```
